### ISSUE TITLE
Timeline view : group_by legend and event display are in opposite orders

### ISSUE THREAD

**Issue by Noezor** [microsoft/msticpy#118]
**Is your feature request related to a problem? Please describe.**
A picture is worth a thousand words. From official documentation example :
![image](https://user-images.githubusercontent.com/8218350/99083377-c3481c00-25c5-11eb-8d3d-577b9aec9425.png)
From top to bottom: 
- on the legend : Bordeaux, blue
- on diplay : blue, bordeaux 

**Describe the solution you'd like**
Have both the legend and display be consistent, it would help a lot when visualizing more events.

I can work on a PR this weekend.

**Comment by ianhelle** [comment]
Since you fixed this, I'll close the issue. Many thanks!
