### ISSUE TITLE
Unclear error messages with Pivots and dataframe

### ISSUE THREAD

**Issue by petebryan** [microsoft/msticpy#159]
When using pivot functions with a dataframe errors caused by incorrect column names are unclear.
If a column name that isn't present in the dataframe is specified the pivot falls back to using the default value rather than telling the user that the columns isn't in the dataframe. This then leads to an error stating the default value isn't in the dataframe instead (if that is the case).

![image](https://user-images.githubusercontent.com/8940401/116944330-24be7e80-ac2a-11eb-8593-e637c31c14fe.png)

**Comment by ianhelle** [comment]
Fixed in PR #170
