### ISSUE TITLE
TI Browser throws exception if no results

### ISSUE THREAD

**Issue by petebryan** [microsoft/msticpy#161]
The TI browser throws an exception if the results data doesn't contain any results of the requested severities. Ideally the browser should display with no results in it.

![image](https://user-images.githubusercontent.com/8940401/117373253-bbd04400-ae7f-11eb-8eb4-1b95e6863bd9.png)

**Comment by ianhelle** [comment]
I've noticed a couple of other place (like the Process tree viz) that also bomb when sent an emtpy data set. We should fix these at the same time.

**Comment by ianhelle** [comment]
Fixed in #140 
TI Browser will throw Value error at the start if supplied with empty (or None) DataFrame
