### ISSUE TITLE
Timeline with an event duration 

### ISSUE THREAD

**Issue by 2xyo** [microsoft/msticpy#166]
Hi,

I would like to display an horizontal bar (start - end) for each event in a timeline. 

Example: in this case, I would like to visualize how long a domain has been seen in passive DNS data: 
```py
import pandas as pd 
import json
from msticpy.nbtools import nbdisplay
data = [{"rrtype": "A", "time_last": 1445413846, "time_first": 1444238290,
   "count": 15, "rrname": "raybaneyeglasses.us.com.", "rdata":
   "151.237.189.86"},
  {"rrtype": "A", "time_last": 1445478986, "time_first": 1443590863,
   "count": 56, "rrname": "abercrombieandfitchoutletsonline.com.", "rdata":
   "151.237.189.86"},
  {"rrtype": "A", "time_last": 1445061327, "time_first": 1444404624,
   "count": 13, "rrname": "furlaoutletsonline.in.net.", "rdata":
   "151.237.189.86"},
  {"rrtype": "A", "time_last": 1444735169, "time_first": 1444302797,
   "count": 42, "rrname": "burberryoutlet.top.", "rdata": "151.237.189.86"},
  {"rrtype": "A", "time_last": 1444948864, "time_first": 1444948864,
   "count": 2, "rrname": "discountnfljerseys.top.", "rdata": "151.237.189.86"}]

df = pd.DataFrame.from_records(data)
df['time_first'] = pd.to_datetime(df['time_first'], unit="s")
df['time_last'] = pd.to_datetime(df['time_last'], unit="s")
nbdisplay.display_timeline(data=df, time_column="time_first", source_columns=["rrname", "rrtype", "rdata", "time_last"], group_by="rrname")

````

So instead of this : 
![image](https://user-images.githubusercontent.com/31675/120857658-e1856180-c581-11eb-9833-5c28fdea5aa4.png)

I would prefer this: 
![image](https://user-images.githubusercontent.com/31675/120857823-27422a00-c582-11eb-98c5-0215d98d87d5.png)

**Describe the solution you'd like**

Add a parameter `time_column_end` to `msticpy.nbtools.timeline.display_timeline`: 

````py
nbdisplay.display_timeline(data=df, time_column="time_first", time_column_end="time_last", source_columns=["rrname", "rrtype", "rdata", "time_last"], group_by="rrname")
````

**Comment by ianhelle** [comment]
Thanks for filing an issue @2xyo. 
At first glance this looks kind of complicated (at least to try to shoe-horn into the current timeline control). Sounds like a good feature though.
Seems like we would need 2 things (I'm kind of designing/thinking out loud):
1. a pre-processing stage where you can generate (for a given column/set of columns) a start_date/end_date pair
2. create a version of the timeline viewer that looks for start/end pairs and plots the bar.

For 1 this is a relatively simple pandas operation -> specify the cols to groupby and generate start (timestamp.min()) and end (timestamp.max()) values.
For 2 plot boxes (or some other glyph) using the start/end coordinates.

I did do a simple version of something like this (in the image below).

![image](https://user-images.githubusercontent.com/13070017/121245790-488e6900-c855-11eb-8a4a-47bcbd953099.png)

**Comment by petebryan** [comment]
I can certainly see value in this idea and I think its something we should start looking at and see how to implement.

**Comment by ianhelle** [comment]
@2xyo I've created a version of this in #176.
Take a look if you get a chance.
It looks quite a lot like your mockup except I've also added the individual event points as an overlay.

**Comment by 2xyo** [comment]
Thanks a lot! (I just add a [minor comment](https://github.com/microsoft/msticpy/pull/176/files#r656856474) in the PR)

**Comment by ianhelle** [comment]
This is now in msticpy 1.3.0

**Comment by 2xyo** [comment]
Thanks @ianhelle :+1:
