### ISSUE TITLE
Replace requests with httpx

### ISSUE THREAD

**Issue by ianhelle** [microsoft/msticpy#172]
Requests is in maintenance mode and has requirements on outdated packages. It also does not support async

We should replace requests with httpx 0.18 throughout the code base.

**Comment by petebryan** [comment]
HTTPX: https://github.com/encode/httpx

Requests is used in a number of places within MSTICPy including:
 - Azure Data features
 - Azure Sentinel API features
 - Mordor Driver
 - ODATA driver
 - Domain Utils
 - TI lookup features
