### ISSUE TITLE
Datetime parameter not working with queries.

### ISSUE THREAD

**Issue by petebryan** [microsoft/msticpy#182]
Created from issues raised on DL:

Currently working with some custom queries in msticpy. However using the datetime parameter seems to not be working. The query runs (gives no errors), but it says that there are no query results. If I copy the query and run it in Log Analytics or MDE, it gives results. Example is with MDE but same applies with LA.
 

Custom query:
![image](https://user-images.githubusercontent.com/8940401/125356303-e07ee700-e31a-11eb-81ca-6cfa9c6c217a.png)
 

Calling it from a query provider in notebook:
![image](https://user-images.githubusercontent.com/8940401/125356318-e674c800-e31a-11eb-895c-13147e0a3749.png)

Same query being ran in MDE:
![image](https://user-images.githubusercontent.com/8940401/125356341-eecd0300-e31a-11eb-95be-011d6486c208.png)

**Comment by ianhelle** [comment]
I think this may be because the query parameter is defined as "start_date" but the parameter used when invoking the query function is "start_time". 
Because start_date has a default value defined, the query provider doesn't complain about missing parameters.

**Comment by petebryan** [comment]
Confirmed resolved in email thread.

**Comment by petebryan** [comment]
Issue uncovered some tangential issues with MDE connector fixed in 1.3.0 -https://github.com/microsoft/msticpy/releases/tag/v1.3.0
