### ISSUE TITLE
MDE should support multiple clouds and regional endpoints

### ISSUE THREAD

**Issue by ianhelle** [microsoft/msticpy#220]
MDE provider currently uses these API definitions
````python
        self.req_body = {
            "client_id": None,
            "client_secret": None,
            "grant_type": "client_credentials",
            "resource": "https://api.securitycenter.microsoft.com",
        }
        self.oauth_url = "https://login.windows.net/{tenantId}/oauth2/token"
        self.api_root = "https://api.securitycenter.microsoft.com/"
        self.api_ver = "api"
````

We need to move these to use cloud-specific endpoints.
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/gov?view=o365-worldwide#api

It would be ideal to support regional endpoints as well.
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-list?view=o365-worldwide

**Comment by ScratZa** [comment]
Hi there 

Would love to assist with regards to this  - new to python so hoping i can try add some value.
