### ISSUE TITLE
Support M365D Hunting

### ISSUE THREAD

**Issue by petebryan** [microsoft/msticpy#221]
**Describe the solution you'd like**
The current MDE integration only support MDE data, by changing the API calls to reach the M365 Hunting API we can support all the M365D data types.

https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-advanced-hunting?view=o365-worldwide

**Comment by ianhelle** [comment]
The linked PR only covers being able to use the new endpoint. It does not include any queries for the broader M365 defender datasets. We should re-open this to work on the latter.
