### ISSUE TITLE
Expand AzureSentinel to include support for other API functions

### ISSUE THREAD

**Issue by petebryan** [microsoft/msticpy#223]
**Is your feature request related to a problem? Please describe.**
AzureSentinel doesn't currently support all the Sentinel REST API features.

**Describe the solution you'd like**
Expand AzureSentinel to support additional features such as the creating and updating of Bookmarks and Watchlists.

**Comment by ianhelle** [comment]
I have some code for Watchlists that will drop into the current AzureSentinel class.
Wonder if we should think of refactoring this class somehow so it's not a behemoth bit of code. Would be nice to have a way of adding new APIs in a generic way, perhaps driven by config or at least some kind of static data structure.
