### ISSUE TITLE
Access Reviews

### ISSUE THREAD

**Issue by nleenold** [microsoft/msticpy#251]
**Is your feature request related to a problem? Please describe.**
I really like the idea behind Access Reviews, but it is very manual in that during the review process, the Reviewer has to manually go an check all the permissions and the access that a user has before they can Approve/Deny. This process is different when doing access reviews for applications, as it lists all the users with access to a particular application.

**Describe the solution you'd like**
It would be time-saving and efficient if the user's permissions would be listed from within the review portal and the reviewer would not have to click around trying to establish the user's access and if its approved or not. This way, it would then be possible to have corresponding Approve/Deny buttons for each permission.

**Describe alternatives you've considered**
A corresponding feature that uses AI and a correlation of sort to flag out suspicious permissions based off on various metrics like results from previous Access Reviews, current role, other users with similar roles and sign-in activity.

**Additional context**
N/A

**Comment by ianhelle** [comment]
@nleenold - sorry to take so long to respond. We've been working with a company called Senserva. 
They have a Python library https://pypi.org/project/Pyserva/ that lets you view and graph access for accounts and groups and also have a sample notebook using this. https://github.com/Azure/Azure-Sentinel-Notebooks/blob/master/Sample-Notebooks/Senserva%20Connections%20Graph%20Notebook.ipynb

@tj-senserva is the brains behind this work. 

I think it would be nice to have some MSTICPy pivot functions that let you use this API to query access for account and group entities.

**Comment by tj-senserva** [comment]
@ianhelle - Thanks for the link

@nleenold - The solution and Notebook we have takes into account several different factors to show Connections that exist, such as a User having a permissions to a particular Application. While it does not currently have the capability to Approve/Deny permissions, we can quickly show you which users have permissions to any Application and cut down the investigation time there. Please feel free to reach out

**Comment by ianhelle** [comment]
I think we'd like to do this ultimately but have no plans/resources to address this in the immediate future
