### ISSUE TITLE
Add support for TIProvider IntSights

### ISSUE THREAD

**Issue by FlorianBracq** [microsoft/msticpy#275]
Intsights (Rapid7) is a Threat Intel Provider can be integrated with msticpy.

https://intsights.com/
https://intsights.com/resources/investigation-api

Sadly, most of the documentation requires an account, thus cannot be shared here.

**Comment by petebryan** [comment]
@FlorianBracq - great suggestion, this isn't a provider I am familiar with but it would be a great contribution!
