### ISSUE TITLE
Legacy VirusTotal API code change to get API key

### ISSUE THREAD

**Issue by danielc-evans** [microsoft/msticpy#288]
With the latest release, the following code: 

vt_key = mas.GetEnvironmentKey(env_var='VT_API_KEY',
                           help_str='To obtain an API key sign up here https://www.virustotal.com/',
                           prompt='Virus Total API key:')
vt_key.display()

No longer takes in the API key as an environment variable or raw value and processes it. 

In order for the key to be accepted with the legacy VirusTotal API, users need to remove the mas dependency: import msticpy.nbtools as mas, and replace with from msticpy.nbtools import nbwidgets. 

Then replace vt_key = mas.GetEnvironmentKey with vt_key = nbwidgets.GetEnvironmentKey

Found this out tonight when trying to run lookups with old legacy api.

If a maintainer could double check my code that would be great.

**Comment by petebryan** [comment]
Hi @danielc-evans thanks for sharing this we will take a look. Just to confirm this issue was in the VirusTotalLookup notebook correct?

**Comment by danielc-evans** [comment]
Yes it was

**Comment by ianhelle** [comment]
Closing since this now a deprecated notebook
