### ISSUE TITLE
Add size attribute to timeline visualization

### ISSUE THREAD

**Issue by ashwin-patil** [microsoft/msticpy#322]
**Problem Statement:**
With the current timeline visualization, each events are plotted with the same size and additional details are available when we hover. It also displays various categories as color pallette which is great. If we can also add size as configurable attribute while plotting, it will be add another dimension to the plot and easily spot outliers in certain types of data where  plotting numeric counts are applicable.

**Potential/expected output:**
Here is an example of scatterplot in seaborn with size as additional attribute. If something similar can be added to timeline, it will be great in certain use-cases.
![Seborn Scatterplot](https://seaborn.pydata.org/_images/scatterplot_21_0.png)

**Comment by ianhelle** [comment]
I've added a partial fix for this. You can manually control the global size of the glyphs with the size=N parameter.
I also added the code that should let you control this from a DF column but that doesn't seem to work. 
I will investigate further.

**Comment by ianhelle** [comment]
Bokeh timeline doesn't seem to work with dynamic glyph sizing in this context. Have added a static attrib for user to control glyph size.
Probably better ways to illustrate this anyway
