### ISSUE TITLE
Use msticpy with Defender and MicrosoftDefender.ipynb 

### ISSUE THREAD

**Issue by mathurin68** [microsoft/msticpy#340]
Are there any articles or directions on using msticpy with Defender?  We don't have Azure Sentinel setup yet.  I am playing around with the MicrosoftDefender.ipynb notebook but keep getting 'key errors'??

I added Microsoft Defender AND Microsoft Graph to msticpyconfig.yaml

Trying Microsoft Defender and it connects...

![image](https://user-images.githubusercontent.com/5932961/158697269-43e4acf8-9dd9-4cf2-857b-8abfde3383d0.png)

List queries works 
![image](https://user-images.githubusercontent.com/5932961/158697616-b5484cf0-dbb9-489e-a045-1514f2234dfc.png)

List Alerts is the start of the error
![image](https://user-images.githubusercontent.com/5932961/158697809-315612a5-5899-490f-bd8d-8e4eca47d2da.png)

Or a hunting query
![image](https://user-images.githubusercontent.com/5932961/158700896-9b61725b-4727-4a35-ac64-09353ea01a67.png)

However, the same query works with the 'Advanced Hunting Using Python' sample code here - 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-sample-python?view=o365-worldwide

... All I really need is an example notebook or a tech community blog.    

I'd appreciate any suggestions!

**Comment by ianhelle** [comment]
Hey @mathurin68 
Thanks for reporting this. It looks like it's a victim of our recent change from using requests to httpx and a bug in the replacement code.
I'm going to get a fix out in the next couple of days but you could try installing 1.6.1 (pip install msticpy==1.6.1) in the meantime.
This was the last release before the httpx replacement and should work.

Apologies for the bug - seems like a gap in our unit tests!

**Comment by mathurin68** [comment]
@ianhelle thank you for the reply! Good to know, I just assumed it was something I was doing.

**Comment by ianhelle** [comment]
Fixed in #345
