### ISSUE TITLE
Handle no data passed to the  display_timeline() function

### ISSUE THREAD

**Issue by mang0kitty** [microsoft/msticpy#360]
## Describe the bug
If no data is returned by a Kusto query and the output of that query is passed to the [`display_timeline` function](https://msticpy.readthedocs.io/en/latest/visualization/EventTimeline.html#discrete-event-timelines) for rendering, the `display_timeline()` function returns a `TypeError` rather than an output indicating that there were 0 records returned from the query. 

**Type Error**
`TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'`

**To Reproduce**
Here are the steps to reproduce the behaviour. 
1. Create query that does not return data for a certain time period. I have provided an obfuscated version of the query we were executing below. Variables in all caps have been replaced.
2.  Convert the output to a  pandas DataFrame
3. Pass the DataFrame to the `display_timeline()` function and execute the query.
4. Repeat with a timeframe that does yield results.
```
startTime= q_times.start
endTime = q_times.end
query = f"""
let suspectHosts = database(DATABASE).Events
| where TIMESTAMP between(datetime({startTime})..datetime({endTime}))
| where isnotempty(rule)
| where rule contains X or rule contains Y
| summarize TriggeredRulesCount=dcount(rule), TriggeredRules=make_set(rule) by Host, ContainerId=tostring(parse_json(output_fields)["container.id"])
| where TriggeredRulesCount == 2;
database(DATABASE).Events
| where TIMESTAMP between(datetime({startTime})..datetime({endTime}))
| where rule contains X or rule contains Y or rule contains Z  
| extend ContainerId=tostring(parse_json(output_fields)["container.id"])
| lookup kind=inner suspectHosts on Host, ContainerId
| project Host, UnderlayName, Rule = rule, TimeGenerated=TIMESTAMP
"""

container_escape_commands = QUERY_PROVIDER.exec_query(query)
container_escape_commands_df = pd.DataFrame(container_escape_commands)
display_timeline(
    container_escape_commands_df,
    group_by = "Host",
    source_columns = ["Rule", "UnderlayName", "TimeGenerated"],
    legend="left",
    height=600,
    width=2000
)
``` 
**Expected behaviour**
Output indicating that the query returned no results. For example:

<span style="color: red;">[⚠️](https://emojipedia.org/warning/)  No data found (0 records).</span>

**Screenshots**
I've removed query to avoid sharing information on specific security events we can see, but the query follows the same format as the one provided above

**Output when no data found for specified timeframe**
![Unsupported Operand Type for NoneType](https://user-images.githubusercontent.com/43414276/163014432-690e220f-82ab-4cbb-a825-6169f8d6add8.PNG)

**Output when data found for specified timeframe**
![DisplayTimeline_With_Data](https://user-images.githubusercontent.com/43414276/163014288-6b31b106-25b6-4f14-9011-08ba94ed2037.PNG)

**Comment by ianhelle** [comment]
This should be fixed in v2.0
