### ISSUE TITLE
Explain need for zsh escaping for extras installs in docs and example notebooks

### ISSUE THREAD

**Issue by aeetos** [microsoft/msticpy#362]
`msticpy` depends on a rarely-used feature of `pip` known as `extras` to selectively install additional packages. These are referenced in a comma-separated list enclosed in square brackets after the base package name. Existing `msitcpy` docs do a great job explaining how to use this feature to activate important features like threat intel providers and connectivity to Azure Sentinel.

Unfortunately, in some OS environments, notably those using `zshell`, the square brackets must be escaped for the installation to complete. If the brackets are not escaped, a warning message is generated that does not help most users resolve the problem:

```
(venv) msticpy-qa > pip install msticpy[azsentinel,vt3,riskiq]
zsh: no matches found: msticpy[azsentinel,vt3,riskiq]
```

A [stack exchange post](https://apple.stackexchange.com/questions/427572/zsh-conflict-with-python-setuptools-extras-and-pip)  explains the situation well. 

This is especially problematic as `zshell` became the default shell on MacOS starting at Catalina 10.15, so this will essentially impact nearly everyone who wants to use the package on a modern Mac (locally, outside of Azure Notebooks). If `zshell` grows in popularity, more users will also be impacted.

Without the ability to install these extras, most users are left with only minimal functionality in the `msticpy` package; addressing this in documentation and example notebooks will ensure everyone gets easy access to these essential capabilities regardless of where they are running the notebook. 

Testing confirms this happens not only at the `zsh` command prompt, but also in a notebook using the `%pip` magic function in a notebook. Screenshot follows:
![screenshot-pip-install-in-notebook](https://user-images.githubusercontent.com/957615/163236119-9f6e3595-2cb0-42bc-b2d4-0c0196c9dfde.png)

We should update `msticpy` docs with a warning about this situation, and also update any example notebooks that include `pip install` commands to offer an alternative (escaped) installation for the extras.

**Comment by ianhelle** [comment]
Need to update any Sentinel notebooks with pip install + readthedocs

**Comment by ianhelle** [comment]
We're updating the notebooks in the Sentinel repo with escaped quotes where we use extras.
I've updated MSTICPy docs with guidance for zshell users.
https://msticpy.readthedocs.io/en/latest/getting_started/Installing.html#selective-installation-using-extras
