### ISSUE TITLE
Config editors demand existing files but lack mechanisms to create them

### ISSUE THREAD

**Issue by aeetos** [microsoft/msticpy#363]
The `msticpy` package must have a configuration file (`msticpyconfig.yaml`) file to function properly, but it lacks the ability to create that file outside an ideal use case that only works in an Azure Sentinel Notebooks environment.

The `init_notebook()` function will create a `msticpyconfig.yaml` file automatically only if a `config.json` file exists in the same directly as the notebook. The `config.json` file is provided by Azure Sentinel only when a template notebook is copied into a user's environment. If a user begins their notebook experience without cloning a notebook, or if they want to use `msticpy` outside Azure Sentinel Notebooks, there is little provision to help them get a functional configuration file. 

Several issues with the package appear when trying to initialize a new notebook environment without a `config.json` file and without a `msticpyconfig.yaml` file. They will be listed here, but the package maintainers are encouraged to re-think the architecture that creates these dependencies and consider alternative ways to bootstrap a notebook environment. 

---

### a.) FileNotFoundError when trying to load the config editor
After running `init_notebook()`, an intuitive way to activate the config editor may look something like this:
```
from msticpy.config import MpConfigFile, MpConfigEdit
mpedit = MpConfigEdit()
```
Unfortunately that returns a `FileNotFound` error because the `msticpyconfig.yaml` file does not exist yet. 

The editor should handle that situation gracefully and load the UI anyway.

### b.) MpConfigFile writes invalid YAML file
Attempting to use the `MpConfigFile` editor to initiate a conf file results in a `msticpyconfig.yaml` file with only curly braces (`{}`). To repro:
1. Ensure no `config.json` file or `msticpyconfig.yaml` file exists in the current directory
2. Initialize the notebook with `init_notebook()` and ensure warnings are raised about the missing config file
3. Activate the settings editor:
```
from msticpy.config import MpConfigFile, MpConfigEdit
mpfile = MpConfigFile()
mpfile
```
4. In the UI, enter `msticpyconfig.yaml` in the "Current File" box
5. Click "Safe file"
6. Ensure the current directory now includes a `msticpyconfig.yaml` file
7. Open the file in a text editor and note the file only contains an open and closed curly brace (`{}`)

The potential for this outcome is referenced in [the msticpy docs](https://msticpy.readthedocs.io/en/latest/getting_started/SettingsEditor.html#checking-your-existing-settings) but the resolution depends on the existence of a `config.json` file.

`MpConfigFile` should avoid writing invalid YAML files, but perhaps a more direct solution is to make `MpConfigEdit` handle the scenario directly, as referenced above.

### c.) init_notebook() fails with `AttributeError` when a blank `msticpyconfig.yaml` file exists
An intuitive way to get the editors working is to write an empty file to the current directory, but this causes `init_notebook()` to fail with an `AttributeError` exception:
```
File ~/dev/msticpy-qa/venv/lib/python3.8/site-packages/msticpy/common/pkg_config.py:83, in refresh_config()
     81 default_settings = _get_default_config()
     82 custom_settings = _get_custom_config()
---> 83 custom_settings = _create_data_providers(custom_settings)
     84 settings = _consolidate_configs(default_settings, custom_settings)

File ~/dev/msticpy-qa/venv/lib/python3.8/site-packages/msticpy/common/pkg_config.py:231, in _create_data_providers(mp_config)
    230 def _create_data_providers(mp_config: Dict[str, Any]) -> Dict[str, Any]:
--> 231     if mp_config.get(_DP_KEY) is None:
    232         mp_config[_DP_KEY] = {}
    233     data_providers = mp_config[_DP_KEY]

AttributeError: 'NoneType' object has no attribute 'get'
```

A similar problem (likely the same block of code) happens if you have an empty `msticpyconfig.yaml` file, skip the `init_notebook()`, and try to start the editors directly, like this:
```
from msticpy.config import MpConfigFile, MpConfigEdit
mpfile = MpConfigFile()
mpedit = MpConfigEdit(settings=mpfile)
mpedit
```
```
AttributeError: 'NoneType' object has no attribute 'get'
```

### d.) MpConfigEdit fails to write settings to config file
To repro:
1. Ensure there is no `config.json` or `msticpyconfig.yaml` file in the current directory
2. Run this code to activate the config editor:
```
from msticpy.config import MpConfigFile, MpConfigEdit
mpfile = MpConfigFile()
mpedit = MpConfigEdit(settings=mpfile)
mpedit
```
3. On the "MicrosoftSentinel" tab, click "Add" under workspaces
4. Leave the value of "Name" as-is, then enter a valid UUID in the other boxes
5. Click "Update"
6. In the "Conf file" box, enter "msticpyconfig.yaml"
7. Click "Save Settings"
8. Ensure the directory now contains a `msticpyconfig.yaml` file
9. Open the `msticpyconfig.yaml` file and note it only contains an open and closed curly brace (`{}`)

The expected behavior is that the settings entered for the workspace are properly written to the file.

### e.) MpConfigEdit needs "Conf file" box populated to save properly
Under several conditions, the MpConfigEdit UI won't write it's settings to a file without the file name populated in the "Conf file" box. This isn't intuitive - it's easy to miss the requirement, click "Save", get no errors, and then realize the file wasn't modified.

**Comment by ianhelle** [comment]
This should be fixed in the linked PR. 
Additional improvements coming for v2.0.0
