### ISSUE TITLE
Store Sentinel workspace name in config file

### ISSUE THREAD

**Issue by aeetos** [microsoft/msticpy#365]
Some interactions with the Microsoft Sentinel API require a workspace name, not just a workspace ID. 

We should store the workspace name in the configuration file (and provide a mechanism to edit it interactively) in addition to the workspace ID. We may also need an easy way of translating between the two internally (so the user can specify either).

This is especially relevant for the `MicrosoftSentinel` objects used to interact with the Sentinel API for important use cases including writing threat intelligence indicators to watchlists. The constructor for that object, and presumably also the API, requires a workspace name, not a workspace ID.

**Comment by petebryan** [comment]
So the ability to add and use WorkspaceName in the config file and for this to be used by MicrosoftSentinel is already there. What we don't currently have is the ability to add this to the config using the config widget - we should add that.
