### ISSUE TITLE
MicrosoftSentinel constructor demands default workspace in config file

### ISSUE THREAD

**Issue by aeetos** [microsoft/msticpy#366]
A `MicrosoftSentinel` class constructed without parameters does not work properly without a "Default" section in the configuration file. The error message is somewhat unhelpful and the self-correction behavior rather unsettling. 

**To repro:**
1. Ensure no `config.json` file is present in the current directory
2. Ensure a `msticpyconfig.yaml` file exists, is formatted properly, has at least one Azure workspace configured, but without a default workspace. For example:
```
AzureSentinel:
  Workspaces:
    TestWorkspace:
      ResourceGroup: rgtest
      SubscriptionId: 3f3fb3df-3c79-4407-8043-4a765430db0e
      TenantId: 3f3fb3df-3c79-4407-8043-4a765430db0e
      WorkspaceId: 3f3fb3df-3c79-4407-8043-4a765430db0e
```
3. Init the notebook, ensure no warnings are generated about the config file:
```
import msticpy
msticpy.init_notebook(namespace=globals())
```
4. Import the class and attempt to instantiate the object:
```
sentinel = MicrosoftSentinel()
```
5. Possibly wait a few seconds, then observe the warning output:
```
Warning
Could not find Microsoft Sentinel settings in msticpyconfig.yaml or a config.json 
(in the current directory or via a MSTICPYCONFIG variable.)
We found the file '../msticpy/dev/config.json' and will use this.
We recommend using an explicit msticpyconfig.yaml specified using the
MSTICPYCONFIG environment variable. See:
https://msticpy.readthedocs.io/en/latest/data_acquisition/DataProviders.html#connecting-to-an-azure-sentinel-workspace
and
https://msticpy.readthedocs.io/en/latest/getting_started/msticpyconfig.html
for more details.
Also see the notebooks:
https://github.com/Azure/Azure-Sentinel-Notebooks/blob/master/ConfiguringNotebookEnvironment.ipynb
https://github.com/Azure/Azure-Sentinel-Notebooks/blob/master/A%20Getting%20Started%20Guide%20For%20Azure%20Sentinel%20ML%20Notebooks.ipynb
```

The code works as expected if a default section exists (although a warning is raised if the WorkspaceName setting is not present, issue #365 should help fix that).

**Expected behavior**
1. If the `msticpyconfig.yaml` exists and a default section exists in the file, use those settings
2. If no default section exists, and only one workspace config is present, use that by default
3. If more than one section exists, use the first one but generate a warning and give the user instructions in how to specify the name of the workspace they want to use

**Bad behavior**
As noted in the output above, the code apparently tries to load a `config.json` file when it can't find a `msticpyconfig.yaml` file it likes, which is okay but will only help those users who have a `config.json` file (see #363). However, performing a search for that file without a warning is unsettling, and searching above the current directory is even more troubling, especially as a side effect of simply instantiating an object.  

At a minimum, the search should be constrained to the current directory; ideally, the search wouldn't happen automatically and only activate when the user adds another parameter.

**Comment by aeetos** [comment]
Confirmed - if you have only one workspace in the file, and that workspace has the WorkspaceName entry as discussed in #365, the constructor will use that workspace automatically and seamlessly. Thanks!

The recursive directory search for a config.json file and confusing error messages will still happen if you have more than one workspace configured and neither are defined as a default. I also encountered additional issues when trying to specify the workspace I wanted using the `workspace=` param, but I'll cover those in another issue or even a PR now that I understand where this is happening.

**Comment by ianhelle** [comment]
Definitely a good time to re-think the way that WorkspaceConfig works.
It might be OK to do this default searching in AML for sentinel users but it's a bit icky to be the default.

Pls open an issue about this and I'll fix it.
________________________________

**Comment by ianhelle** [comment]
It's funny actually, in the v2 work I've been revisiting a bunch of code that is among the oldest in msticpy - a lot of stuff that I wrote when I wasn't really very sure of Python and mostly used a hammer to get things working.  It's like dev archeology. The WorkspaceConfig code is mostly in that category.

________________________________
