### ISSUE TITLE
Generate GeoIP map directly from dataframe

### ISSUE THREAD

**Issue by aeetos** [microsoft/msticpy#367]
Map visualizations for IP location are a common use case for cyber security analysts, and `msticpy` enables this through the FoliumMap class and the various methods to lookup GeoIP data for a list of IPs.

Currently, it can be difficult to discover the necessary commands to go from a list of IP addresses represented as strings to pins on a map, especially if you want to include tooltips that offer context on those IPs. 

We should consider building a mechanism that can create a map directly from a dataframe with IP addresses in it (represented only as strings). 

Ideally something as simple as:
```
from msticpy.nbtools.foliummap import FoliumMap
folium_map = FoliumMap()
folium_map.add_dataframe(df, column='IP')
display(folium_map)
```

Implementation ideas (credit to @ianhelle for these):
- If lat/long fields exist, use those directly
- Else, do geolocation on an IP string found in a column specified in the function params
- Let users define which dataframe columns can provide details for pop-ups/hovers on pins
- Possibly do icon mapping based on field criteria
- Possibly print out names of icons?
- Build it as a DF accessor that can accept a map object and add additional data sets
- Allow adding folium layers by one of (specify column, function, mapping to ID layer) or (statically name layer in DF parameter so you can apply multiple DFs as named layers)

**Comment by ianhelle** [comment]
@aeetos - I've re-written a lot of this module and added the ability to plot from a DF. Also a bunch of other usability improvements.
