### ISSUE TITLE
Dns resolutions should return individual records per row

### ISSUE THREAD

**Issue by ianhelle** [microsoft/msticpy#386]
When used as a pivot function dns resolution returns multiple records as a list object. This should be individual rows per record.

**Comment by petebryan** [comment]
Looking at this and we basically want to explode the rrset column right?
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/8940401/180079256-c22d4e48-f809-463f-9e03-3d98e6d9763c.png">
