### ISSUE TITLE
Improve default behavior in WorkspaceConfig for config file source and workspace selection

### ISSUE THREAD

**Issue by aeetos** [microsoft/msticpy#388]
The `WorkspaceConfig` class in `wsconfig.py` is leveraged by several modules, including those providing the `MicrosoftSentinel` class, to find configuration details for Azure Sentinel workspaces in config files.

Those config details can come from multiple places, and `WorkspaceConfig` tries to help by making decisions about the optimal file, file location, and yaml list item to load those settings from, but the logic behind those decisions could be improved to better reflect scenarios users will encounter when they first start using `msticpy`. 

One such issue was already fixed in #366 but the work there has shown the value of a more concerted effort to re-visit how this works.

We should settle on a prioritized list of config sources, then agree on default behaviors that can deliver out-of-the-box functionality in typical use cases without complex code or unexpected side effects. Some of this may exist already; we're defining it at a high level here so we can then review individual files and decide whether their code will fulfill our intentions. 

**Prioritized config sources** (proposed):
1. YAML file at a path (with filename) defined in an optional parameter passed to `init_notebook`
2. YAML file at a path (with filename) defined by the `MSTICPYCONFIG` environment variable
3. YAML file named `msticpyconfig.yaml` in the current directory
4. YAML file named `msticpyconfig.yaml` in the `msticpy` config directory (see #375)
5. `config.json` file in the current directory

> NOTE: it is unclear whether the design intent is for the `MSTICPYCONFIG` environment variable to support either a YAML file or a `config.json` file. It should only work for YAML files; if we need to support an environment variable to point to a `config.json` file it should ideally be a different variable name.

We should not be expected to support a "split config" scenario where some settings come from a local `msticpyconfig.yaml` file and others come from a local `config.json` file. Once we choose a configuration source, we should stick with that and expect the user to either move it out of the way or populate it with everything we need. For example, if we select a config source but it doesn't have an AzureSentinel config section, we should stop, tell the user the issue, and guide them to fix it. 

The recursive above-current-directory search for a `config.json` file may be necessary in an Azure Sentinel context, but it should ideally only be triggered when the notebook is known to be running in that environment. Otherwise, it should only activate on user request with a parameter.

**Workspace Selection Logic** (proposed):
1. If a `workspace` parameter is specified in a constructor, find the workspace section in the YAML file that matches that name (or perhaps, if we are using a config.json file, the workspace name defined in that file). If no name is found, raise an exception that possibly includes a list of workspaces to choose from.
2. Else, if no param is specified:
  a. If only one workspace is defined in the config source, choose that one, even if it is missing required fields.
  b. If more than one workspace is defined in the config source, but one of them is listed as default, choose the default, even if it is missing fields.
  c. If more than one workspace is defined in the config source, but none of them are listed as default, raise an exception. The exception message should explain how to either mark the workspace as default or provide the name in the parameter. Consider listing the available workspace names in the exception to help as in 1 above.
3. After choosing a workspace based on this logic, if necessary fields are missing (i.e. the workspace name), raise an exception and provide guidance. This is preferred over skipping an incomplete workspace config and choosing something else.

> NOTE: The current code uses a variety of parameter names that may refer to the actual workspace name or a section in the config file. They likely need to be preserved for backward compatibility, but if possible we should choose some standard or more explicit names. Also consider specifying them in classes like `MicrosoftSentinel` that currently pass extra params to `WorkspaceConfig` in `kwargs` which are difficult to document and discover.

**Comment by ianhelle** [comment]
We're working on these issues in a few places.
- the config.json search we'll probably abandon or just include for AML users. I agree on trimming the search scope since this could find config.json files for other users in the AML folder structure.
- Sentinel APIs will try to get the default workspace if no params are supplied.
- I'm building a helper module that will:
  - derive all of the workspace config info from a portal URL (i.e. go to Sentinel portal, copy and paste it into the tool)
  - workspace name <--> id resolution - we'll have this as a utility and will integrate into setup UI
- Sentinel workspace settings now have workspace name, we should be able to derive the full workspace info from tenantID + workspace ID (or maybe workspace name + subscription ID).
- msticpyconfig resolution
  - looks for ENV var first
  - looks in ~/.msticpy next
  - looks in current folder next
-  init_notebook will support a `config` parameter to specify a msticpyconfig file that will override the above resolution.
