### ISSUE TITLE
Provide links to where you can register for the TI and GeoIP APIs

### ISSUE THREAD

**Issue by titanicshark** [microsoft/msticpy#389]
**Is your feature request related to a problem? Please describe.**
Yes. I find it difficult to get the APIs working as I don't know what values which each provider chucks out go where, in respect to the config yaml. It would be useful to add to the README and or docs links to where you can register for the various supported Threat Intelligence and GeoIP APIs, in addition with detail on how to use them.

**Describe the solution you'd like**
Add to the README or repo docs a list of links to where you can register for the various supported Threat Intelligence and GeoIP APIs with usage details.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by ianhelle** [comment]
We do have this in documentation and notebooks but it's difficult to keep up with changing vendor sites.
Will try to keep current links updated
