### ISSUE TITLE
MPConfigFile throws ValueError at load

### ISSUE THREAD

**Issue by ianhelle** [microsoft/msticpy#393]
**Describe the bug**
ValueError on line 140 - 

**To Reproduce**
TBD

**Expected behavior**
No error is thrown - default config is loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/13070017/167454462-5b990a5d-ef9d-4ccb-acd7-92532bc6cb70.png)

**Desktop (please complete the following information):**
- Azure ML

**Additional context**

**Comment by kenshukubo** [comment]
I run "%xmode verbose" before the erroring cell. 

![スクリーンショット 2022-05-10 8 48 21](https://user-images.githubusercontent.com/72034378/167516191-ec59ae81-afc2-4651-a2e9-d2170759076e.png)

![スクリーンショット 2022-05-10 8 44 44](https://user-images.githubusercontent.com/72034378/167516004-494ffdc7-36b7-41c9-a445-abb032c6cef9.png)

**Comment by ianhelle** [comment]
I think I found the problem and fixed it here https://github.com/microsoft/msticpy/commit/252dd183403b72a2e1dd179a9fd3607ad6d96830

I accidentally committed it to main. If all goes well I'll try to get new release tomorow.

**Comment by Lopa2016** [comment]
I am still getting an error not with the config file but while querying the data. Have created a new issue on git . https://github.com/microsoft/msticpy/issues/398

**Comment by kenshukubo** [comment]
me too
