### ISSUE TITLE
Unable to connect to the data source using query provider

### ISSUE THREAD

**Issue by Lopa2016** [microsoft/msticpy#398]
**Describe the bug**
ClientAuthenticationError at line 6

**To Reproduce**

**Expected behavior**
No error is thrown connects successfully to Azure 

**Screenshots**

<img width="624" alt="IssueMISTCPy" src="https://user-images.githubusercontent.com/33491250/167814287-dc97dccd-ab34-4d1b-9210-741ea3b3c2fe.png">

**Desktop
 - Azure sentinel notebook

**Additional context**

**Comment by ianhelle** [comment]
Argh! Sorry about this. I'm on vacation until 17/5 - maybe @petebryan can help diagnose.
You can force the earlier version of msticpy by replacing the line in the "ïnitializing notebooks" section (a couple of cells prior to the error)
```
%pip install --upgrade --quiet msticpy[azuresentinel]
```
with this.
```python
%pip install msticpy==1.7.5
```
We'll get it fixed (and get our testing a bit tighter for the notebooks - not sure how we missed both of these.)

**Comment by Lopa2016** [comment]
> Argh! Sorry about this. I'm on vacation until 17/5 - maybe @petebryan can help diagnose. You can force the earlier version of msticpy by replacing the line in the "ïnitializing notebooks" section (a couple of cells prior to the error)
> 
> ```
> %pip install --upgrade --quiet msticpy[azuresentinel]
> ```
> 
> with this.
> 
> ```python
> %pip install msticpy==1.7.5
> ```
> 
> We'll get it fixed (and get our testing a bit tighter for the notebooks - not sure how we missed both of these.)


Thanks Ian :)

**Comment by kenshukubo** [comment]
I get this error
Fixed version has been released?

**Comment by kenshukubo** [comment]
@Lopa2016 
I get this error
Fixed version has been released?
