### ISSUE TITLE
Getting Started with Azure ML Notebooks and Microsoft Sentinel ISSUE [MSTICPY CONFIG EDITOR DISPLAYING INCORRECTLY]

### ISSUE THREAD

**Issue by ryanoleary1** [microsoft/msticpy#404]
**Describe the bug**
There appears to be an issue with how the MsticPy configuration editor [MpConfigEdit()] displays within a web browser. More specifically- the GUI display appears to be stuck on the "workspace settings" tab and will remain stuck, even when you switch to different tabs e.g. "TI Providers", "Data Providers" etc. This issue DOES NOT occur- when you run the code directly within visual studio code.

**To Reproduce**
1. Open web browser (Chrome or Edge)
2. Within MS Sentinel- create a ML workspace and open the _"Getting Started with Azure ML Notebooks and Microsoft Sentinel" notebook_
3. Create a compute instance
4. Complete _"Getting Started with Azure ML Notebooks and Microsoft Sentinel"  notebook steps  1-3.1
5. When running the code in step 3.2 and 4.1 [launching the MPEdit GUI] the GUI does not display properly
![image](https://user-images.githubusercontent.com/60218128/168650042-da0e0b48-87b1-45b0-9fd0-cfd4d002b5eb.png)

**Expected behavior [Visual Studio Code]**
These screenshots were taken from when I ran the code in visual studio code editor- where the MSEditor renders as expected. Note each tab in the editor renders different menu options
![image](https://user-images.githubusercontent.com/60218128/168652621-08ca5e8c-2c6c-42aa-917c-9c5e1b9e7803.png)

**Screenshots of Issue [Microsoft Azure Machine Learning Studio]**
These screenshots were taken when executing the notebook code directly in the web browser via Microsoft Azure Machine Learning Studio. Note: Irrespective of which tab in the is selected- the editor always displays the "workplace settings" menu. Not only this- none of the buttons within the workspace settings options appear to work either. This prevents users from configuring settings such as TI, Azure Key Vault,  GEOIP, via the GUI.

![image](https://user-images.githubusercontent.com/60218128/168654198-520ed511-5c87-4234-a7d0-17904eea31c3.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [tired Chrome and Edge]
 - Version [Chrome Version 101.0.4951.67]
 - Compute Instance Kernel 3.8

**Additional context**

Hi, I am a brand new user of Azure Sentinel Notebooks. Although- I was able to resolve this issue by opening the notebook in visual code editor- this may be an issue for other new notebook users. Especially- because configuring the msticpiconfig.yaml file is vital for most of the "out of the box" notebook templates. Note: I have also reported this issue separately on the following github link https://github.com/Azure/Azure-Sentinel-Notebooks/issues/152

Thanks in advance- Ryan

**Comment by petebryan** [comment]
Thanks @ryanoleary1 I will investigate.

**Comment by petebryan** [comment]
This appears to be an issue with AML not correctly updating the widget when you select a new tab. I will esclate to that team.

**Comment by petebryan** [comment]
This has been fixed by AML.

**Comment by ryanoleary1** [comment]
Hi Pete,

Thank you very much for arranging for this to be fixed

Cheers,
Ryan
