### ISSUE TITLE
Generating process tree using alternative data source

### ISSUE THREAD

**Issue by ianhelle** [microsoft/msticpy#446]
### Discussed in https://github.com/microsoft/msticpy/discussions/439

<div type='discussions-op-text'>

<sup>Originally posted by **blueteam0ps** June 11, 2022</sup>
Hi there,
I got a quick question regarding creating a process tree based on an alternative data source. I understand that this will require me to copy an existing schema and make one for my source data set. 

Following is the dataframe which I would like to create a process tree of.
![Notebook](https://user-images.githubusercontent.com/1480956/173188258-8a993527-0c7a-4408-9a6f-7fbbb38f20ec.jpg)

I referred to this https://github.com/microsoft/msticpy/blob/c66a03fdd376c86b3ce3af266a91c6cf53c0d3fd/docs/source/visualization/ProcessTree.rst#adapting-the-input-schema-of-your-data to create the following.

Do you think this is the correct way to achieve what I need ? 
```python
    from msticpy.sectools.proc_tree_builder import WIN_EVENT_SCH
    from copy import copy
    dfprocs_renamed = dfprocs.rename(columns={'PID': 'process_id', 'PPID': 'parent_id', 'ImageFileName': 'process_name', 'CreateTime': 'time_stamp',  'PPIDName': 'parent_name'})
    procs_rmcolumns = ['TreeDepth', 'Offset(V)','Threads','Handles','SessionId','Wow64','ExitTime']
    dfprocs_renamed.drop(procs_rmcolumns, inplace=True, axis=1)  
    cust_win_schema = copy(WIN_EVENT_SCH)
    cust_win_schema.time_stamp = "time_stamp"
    cust_win_schema.process_name = "process_name"
    cust_win_schema.process_id = "process_id"
    cust_win_schema.parent_name = "parent_name"
    cust_win_schema.parent_id = "parent_id"
    cust_win_schema.logon_id = None
    cust_win_schema.cmd_line = None
    cust_win_schema.user_name = None
    cust_win_schema.path_separator = None
    cust_win_schema.host_name_column = None
    cust_win_schema.event_id_column = None
    cust_win_schema.event_id_identifier = None
    process_tree.plot_process_tree(dfprocs_renamed, schema=cust_win_schema)
```
</div>

**Comment by ianhelle** [comment]
@blueteam0ps
Can you upload a bit of the data?
Feel free to obfuscate.

**Comment by blueteam0ps** [comment]
@ianhelle  Please refer attached a sample csv.
[sample_procout.csv](https://github.com/microsoft/msticpy/files/8927212/sample_procout.csv)
