### ISSUE TITLE
Better Error Reporting and Timeout for KQL Query Provider

### ISSUE THREAD

**Issue by ashwin-patil** [microsoft/msticpy#451]
**Describe the bug**
Currently Msticpy allows to connect to Data Environment such as Sentinel and once connected it can execute KQL queries. In some cases when KQL query returns large set of records the friendly error returned is not informative about and needs more details for user to troubleshoot. 

**To Reproduce**
1.  Import msticpy and initialize the query provider
2. Connect to Sentinel workspace. 
3. Execute query which can return large set of records preferably with set notruncation option from a table such as SecurityEvents, CommonSecurityLog etc.
4. You may see an error as shown in the below screenshots. 
5. Try to display the dataframe in another cell - optional. 

**Expected behavior**
The Error returned should have clear description what went wrong executing the query. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11397335/174417593-35694bfc-0550-461e-9e36-eb17c6def66c.png)

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser : Chrome, Edge
 - Version: Edge 102

**Comment by ianhelle** [comment]
Should implement Florian's code or defer to #510

**Comment by ianhelle** [comment]
Added ability for use to set custom timeout.
