### ISSUE TITLE
Mandiant Threat Intelligence API integration 

### ISSUE THREAD

**Issue by titanicshark** [microsoft/msticpy#458]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Mandiant to be a Threat Intelligence provider so you can search by threat actor, malware report types, threat actors in a given country, object references, IoC and IP address and get details in a dataFrame of what Mandiant has returned. This data will enhance the threat intelligence analysts and data scientists have and help give a better view and understanding of the threat landscape they are dealing with.

**Describe alternatives you've considered**
None

**Additional context**
To access the API, you request a free Mandiant Threat Intelligence account which is available to professionals in security, each account request is approved by Mandiant manually. Once you have the account you can get your key in the Mandiant Threat Intelligence platform via your browser. The docs for the API are here https://api.intelligence.fireeye.com/docs. Mandiant acquired FireEye hence it's the FireEye API.

**Comment by ianhelle** [comment]
No free tier makes this difficult to dev/test
