### ISSUE TITLE
Installation error geoip

### ISSUE THREAD

**Issue by guidovbrakel** [microsoft/msticpy#467]
**Describe the bug**
```
ERROR: geoip2 4.6.0 has requirement requests<3.0.0,>=2.24.0, but you'll have requests 2.22.0 which is incompatible.
ERROR: nbconvert 6.5.0 has requirement jinja2>=3.0, but you'll have jinja2 2.10.1 which is incompatible.
```
**To Reproduce**
`python3 -m pip install msticpy`

**Desktop (please complete the following information):**
Ubuntu 20.04 server

**Comment by ianhelle** [comment]
I think you'd be OK to ignore the nbconvert as far as msticpy is concerned - we don't have any dependencies on it (although we use it in some unit tests).
We also don't use requests so you are free to upgrade this to >=2.24.0. 
We don't use any of the geoip2 network functionality so you probably won't hit any compatibility problems here if you just ignore it.

These are all comments with respect to msticpy - I can't speak for other dependencies that you might have installed.
To check what other packages have dependencies you can run `pip show requests` or `pip show nbconvert`.
I usually err on the side of upgrading to the latest versions unless there is some cast-iron compatibiity problem.

The other thing (which should reduce incompatibilities) is to install and use msticpy in a separate Python virtual environment. 
See https://msticpy.readthedocs.io/en/latest/getting_started/Installing.html#creating-a-virtual-environment

The instruction to activate the venv in this doc isn't quite right - it should be `source ./venv/scripts/activate`
