### ISSUE TITLE
Enabled query "printing" without being connected.

### ISSUE THREAD

**Issue by FlorianBracq** [microsoft/msticpy#469]
**Is your feature request related to a problem? Please describe.**
When using the "print" argument to display a query, the provider must be connected. While this workflow is expected when the query should be executed, it does not make much sense when the user only requires to view what would be executed.

**Describe the solution you'd like**
I see 2 possibilities for this:
* Create a new dedicated function for printing
* Update the function _execute_query to have the query built outside of this function

**Additional context**
I do not know yet how "print" and "split_query_by" should behave? Displaying 10s of queries with just a the time window modified might not cover the "standard use", but could still be relevant in some corner cases.

**Comment by ianhelle** [comment]
I've fixed this to bypass the requirement to be connected when the user is only displaying help or outputting the debug "print" parameterized query.
