### ISSUE TITLE
loganalytics_uploader (LAUploader) not optimal for "long" files

### ISSUE THREAD

**Issue by pensivepaddle** [microsoft/msticpy#486]
**Describe the bug**
The way it currently transforms a csv to a list of dicts is less than optimal wrt time used (i.e. a file of 15 MB with 1M lines ran for an hour to iterate through first 100k lines).

**To Reproduce**
1. Go to an archived version of `hxxp://s3.amazonaws.com/alexa-static/top-1m.csv.zip` (or similar) and unzip
2. Initialize the necessary (as described in the [docs](https://msticpy.readthedocs.io/en/latest/data_acquisition/UploadData.html)) and attempt uploading of the extracted csv (1M lines), i.e.
`laup.upload_file(file_path="./top-1m.csv", table_name="alexa_top_1m")`
3. See it run "forever"

**Expected behavior**
Fairly fast upload of the data.

**Screenshots**
Screenshot shows (with added debug messages with count of "converted" rows, after first run withoutit (and no progress info) ran for >30 min with no end in sight. Screenshot indicates an estimated avg. processing frequency of 15 lines per second, meaning 18 hours for a file of 1M lines (still only 14 MB in size)

![laupload](https://user-images.githubusercontent.com/104833713/184135066-e5e81ae3-c9d0-45c2-8ded-0f25b8015186.png)

**Desktop (please complete the following information):**
 - OS: macOS, M1
 - IDE: VSCode (Jupyter)

**Additional context**
Did a simple workaround utilising something along the lines of an answer on SO ([link](https://stackoverflow.com/a/21572244)) which finished in seconds. The combined json body is > 25MB though, solved by splitting the resulting "events" in two posts, but there are better solutions to that.

***Slight sidenote***
It currently converts all csv columns to strings, regardless of the actual content. The REST API accepts "integers" in the POST as well, which propagates to the LA table (verified). Perhaps the type identified by Pandas within the DataFrame (as it goes through it either way) would be nice?

**Comment by petebryan** [comment]
Thanks for raising @pensivepaddle - we have a task to go and update this feature (as there is now a better way of uploading logs), and so I will make sure I take this into consideration and ensure any update is much more performant.

**Comment by jllangley** [comment]
I have made some updates to this code under PR 633
 https://github.com/microsoft/msticpy/pull/633
Feel free to use this code or modify it as needed.
