### ISSUE TITLE
Provider formatters for JSON queries

### ISSUE THREAD

**Issue by FlorianBracq** [microsoft/msticpy#529]
Multiple providers (such as Elastic or Cybereason) uses JSON-formatted queries.
Other providers (such as Kusto-based providers) rely on a specific query language that can be formatted as a string of text.

Today, Msticpy query_source mostly expect string-formatted queries to detect and set parameters dynamically (through str.format() or regular expression analysis).

While the elastic driver provides an example of a custom "param formatter", it does not fully support JSON-based queries.

While strings are properly handled, integers and lists are transformed to string which can lead to either an invalid JSON, or incorrect queries.

One "easy" way out is to type all parameters as "string" to ensure they are not formatted and let json.loads()/json.dumps() methods handle typing properly but that does not sound ideal.

I will soon share a new branch around Cybereason driver modified to (somehow) support JSON queries, but there are a few caveats that are worth discussing before merging.
Happy to hear comments/feedbacks on it!

Additional details;
* function _format_parameter in query_source.py will always format a list as a string, which is not the desired behavior for a JSON object.

**Comment by ianhelle** [comment]
@FlorianBracq 
We do already have such a formatter - in the half-written data.drivers.elastic.py driver. I wrote this for Neil who was working on an ES data provider.
https://github.com/microsoft/msticpy/blob/4451555473e063f5b9662aec9ac3f5ad585046a1/msticpy/data/drivers/elastic_driver.py#L175

This is somewhat specific to elastic search syntax but works as follows::
- The query string is stored as a multi-line json string in the query.yaml file
- Time params are added as values to the range element
- Parameters are substituted in the "query.bool.filter.match_terms" element - this gives simple pattern matching
-  add_query_items are also added to the match_terms dict
It isn't perfect but seems to work in a limited way.

**Comment by FlorianBracq** [comment]
@ianhelle:
As this was not working reliably, I tried to implement a different (probably more complex too...) version here > https://github.com/FlorianBracq/msticpy/tree/Cybereason_json

The few changes I tried to address:
* Define a query as a valid JSON string
  * Helps "copy-pasting" queries without having to escape all curly braces
  * Easier to read/debug when the JSON is not valid
* Support For "nested" queries by searching for keys to replace in the JSON
  * As Cybereason data source has a rather organic structure, replacing the parameters is not as direct as it is for Elasticsearch
  * It follows the same structure as other queries, so it's probably easier to use?

Let me know if it's worth raising a PR for :)
