### ISSUE TITLE
Implement dependency version limits

### ISSUE THREAD

**Issue by ianhelle** [microsoft/msticpy#551]
**Is your feature request related to a problem? Please describe.**
We want to strike a balance between keeping up with version changes for our major dependencies but provide stability so that a given version of msticpy will work with a specified dependency version.

**Describe the solution you'd like**
Pin dependency ranges of most/all dependencies to current lower version and an upper version that is less than the next major release.
(e.g. dep>=1.2.4; <2.0.0)

This should at least target the major MSTICPy depndencies:
- pandas
- bokeh
- numpy
- IPython
- ipwidgets
- some azure core SDKs

We also want to implement a special build that opens these upper limits to flag breaking changes in the latest dependency versions - so that we are aware that we need to do something to support a major version change.

**Describe alternatives you've considered**
The alternative of *only* setting lower bound (what we currently do) means that we a frequently chasing breaks when a dependency upgrades with breaking changes. 

**Additional context**
We will continue to trust that dependencies honor semantic versioning and only make breaking changes on major release numbers.
We realize that isn't universally adhered to but the proposal will at least reduce the firedrill of having to release a hotfix for this issue quite so frequently.

**Comment by petebryan** [comment]
Another alternative is pinning on specific versions - this would let us specify specific package hashes, improving security but significantly limiting compatibility when using MSTICPy in an environment with other packages. I would suggest this is an alternative we should consider but I don't think it's the solution we should proceed with.
