### ISSUE TITLE
[Bug]: IPython.notebook.kernel.execute errors from QueryProvider

### ISSUE THREAD

**Issue by kenshukubo** [microsoft/msticpy#572]
Describe the bug
Currently running the msticpy 2.1.5.

When the QueryProvider module is connecting to the LogAnalytics workspace to run a query I am getting this error.
'''

try {IPython.notebook.kernel.execute("NOTEBOOK_URL = '" + window.location + "'");} catch(err) {;}

'''

**Comment by petebryan** [comment]
Hi @kenshukubo are you running this notebook in Azure Machine Learning?

**Comment by kenshukubo** [comment]
@petebryan  Yes

**Comment by ianhelle** [comment]
This is an Azure ML/Azure notebooks issue. They did roll out a fix but had to revert it because of some regression.
We have a potential workaround for it but ideally would like them to fix it. Will prob wait a week and see what happens on their end.

**Comment by ianhelle** [comment]
Should be fixed in 2.3.1
We have waited for ages for AzureML/azure notebooks to fix this but hopefully, this workaround will remove the problem (at least from Kqlmagic output)
