### ISSUE TITLE
 [Errno 101] Network is unreachable` msticpy 2.1 and above...

### ISSUE THREAD

**Issue by mathurin68** [microsoft/msticpy#573]
I'm not sure if this is a bug... or probably, something I have configured wrong on our server.  

On Ubuntu 20.04, msticpy 2.1 and up I get the following error when importing msticpy.  
`ConnectError: [Errno 101] Network is unreachable`

Importing msticpy 2.0.0 works great, but I can't take advantage of the ability to access the GCC api in 2.2
mde_prov = QueryProvider("MDE", cloud="gcc")
https://github.com/microsoft/msticpy/pull/525

I'd appreciate any suggestions! 

Attached is the full error...
[network_error.txt](https://github.com/microsoft/msticpy/files/10009236/network_error.txt)

**Comment by ianhelle** [comment]
Thanks @mathurin68.
We have fixed this bug but not yet published in #568.
The "fix"is to move the network request so that it's only triggered on whois lookup.
It will be triggered when either no network is available or if running in a restricted network environment.
Seems like it would be good to make this lookup optional in any case - tagging @petebryan for his thoughts.

**Comment by petebryan** [comment]
Yeah fully agreed we shouldn't have any external lookup as a dependency on using the package if we can avoid it.

**Comment by ianhelle** [comment]
I moved this code to only run when a whois query is run. @petebryan - do you think this is enough or should we make it bypass this if the lookup fails?
Obvs if you are completely offline, whois lookups are going to fail anyway so it may be moot. Just wonder if we want the whole thing to fail if cymru decide to do something weird with their API.

**Comment by mathurin68** [comment]
Everything appears good..
![image](https://user-images.githubusercontent.com/5932961/205337932-e56243d5-e06e-4bcd-a073-0f5940d94681.png)

As always thank you for all this!  And good start to Jupyterthon, watching it now!!!
