### ISSUE TITLE
Inbuilt function to extract nested JSON in AuditData field in M365 UAL logs

### ISSUE THREAD

**Issue by blueteam0ps** [microsoft/msticpy#589]
This is a feature request

- UAL CSV log export generated from M365 portal contains a column named "AuditData". It contains nested JSON and has multiple dicts.  This column contains all the valuable data for investigations. It would aid analysts to have data within this column expanded so that it can easily be manipulated to answer questions during investigations.
- In a scenario where API connectivity is not possible, then the log exports are used for carrying out analysis
- Proposing a feature request so that msticpy's existing QueryProvider LocalData can be further improved to resolve this.

Uploaded a sample export from M365 UAL (https://github.com/invictus-ir/o365_dataset)
[auditrecords.csv](https://github.com/microsoft/msticpy/files/10144657/auditrecords.csv)

**Comment by ianhelle** [comment]
We do have some functions like this in msticp.init.pivot_core.pivot_pd_accessor.py. (see the parse_json function)
Sounds like we could extend this kind of thing (or move the accessor functions to something more generic that pivots) to do this elementary dict-in-a-dataframe extractor.
Something like:
df.mp.dict_to_columns(column="AuditData")

I realize that the AuditData can be a mix of lists and columns so it might need to do a combo of column expansion and explosion of rows but it seems doable.

**Comment by blueteam0ps** [comment]
> We do have some functions like this in msticp.init.pivot_core.pivot_pd_accessor.py. (see the parse_json function) Sounds like we could extend this kind of thing (or move the accessor functions to something more generic that pivots) to do this elementary dict-in-a-dataframe extractor. Something like: df.mp.dict_to_columns(column="AuditData")
> 
> I realize that the AuditData can be a mix of lists and columns so it might need to do a combo of column expansion and explosion of rows but it seems doable.

Sounds great!

**Comment by pioneerHitesh** [comment]
I am interested in contributing in to this, can this be assigned to me?

**Comment by ianhelle** [comment]
Hey @pioneerHitesh, 
This is a long time ago but if you're still interested in this, it would be very cool to have.

**Comment by pioneerHitesh** [comment]
> Hey @pioneerHitesh, 
> This is a long time ago but if you're still interested in this, it would be very cool to have.

I am still willing to give this a try.

**Comment by pioneerHitesh** [comment]
@ianhelle i am interested. Please do assign this to me

**Comment by pioneerHitesh** [comment]
@ianhelle i would like to give this a try, can this be assigned to me.
