### ISSUE TITLE
[Bug]: Search on ReadtheDocs for msticpy is not working

### ISSUE THREAD

**Issue by ashwin-patil** [microsoft/msticpy#643]
**Describe the bug**
Search on the readthedocs for msticpy is not working.

**To Reproduce**
- Go to readthedocs site for msticpy - https://msticpy.readthedocs.io/en/latest/
- search for any relevant keyword related to msticpy
- It keeps on searching and never finishes
- I already tried from different browsers and clearing cache.

**Expected behavior**
Search should return relevant results in due course of time.

**Screenshots and/or Traceback**
<img width="807" alt="image" src="https://user-images.githubusercontent.com/11397335/225683650-32634173-57d0-4fb0-8bd4-6045b2b5a303.png">

**Environment (please complete the following information):**

- OS: Windows
- Browser - Edge/Chrome/FireFox

**Comment by ianhelle** [comment]
Fixed in RTD doc build 16/5/2023 - checked directly into main
