### ISSUE TITLE
check and update MaxMindDB appears to be failing silently

### ISSUE THREAD

**Issue by beerMT** [microsoft/msticpy#66]
For the function _check_and_update_db, I am troubleshooting the following:
`iplocation = GeoLiteLookup(api_key=value, db_folder = Path('./max_mind_db/'), force_update=True)`
- API key is valid
- GeoLiteLookup is able to pull the current path and run IP lookups against the stored DB
- Output is "Latest local Maxmind City Database present is older than 30 days. Attempting to download new database to max_mind_db"
- When VScode electron app reaches out to maxmind, I whitelist it
- No additional error codes or failures are presented and I would have expected this elif block of code to fire since force_update is set to True
`elif force_update and auto_update:
                print(
                    "force_update is set to True.",
                    f"Attempting to download new database to {db_folder}",
                )
                try:
                    db_is_current = self._download_and_extract_archive(url, db_folder)
                except MsticpyConfigException as no_key_err:
                    warnings.warn(" ".join(no_key_err.args))` 
- Result - I don't see the message "force_update is set to True. Attempting to download new database to {db_folder}" and the MaxMind DB is not updated and keeps previous timestamp 

Any help would be greatly appreciated! Been fun test driving this python tooling, thanks infosec Jupyterthon :)

**Comment by beerMT** [comment]
Included is a Wireshark capture where connection is established to maxmind and data transfer occurrs.
<img width="1920" alt="Screen Shot 2020-05-26 at 10 21 29 PM" src="https://user-images.githubusercontent.com/6117308/82977629-abd99000-9f9f-11ea-9673-7c91609c3e57.png">

**Comment by ashwin-patil** [comment]
Thanks @beerMT for trying out msticpy and GeoIP feature. 
Could you tell us more about your environment where it is silently failing so we can reproduce ? 
I did not understand the 4th point about whitelist. 

Below code is working (download and extract db) when i tried to reproduce in my environment, with old db and first time db set-up. 

```python
from msticpy.sectools import GeoLiteLookup
from pathlib import Path
iplocation = GeoLiteLookup(api_key='<api-key>', db_folder = Path('./max_mind_db/'), force_update=True)
```

**Comment by beerMT** [comment]
The whitelist comment is specific to running in vscode, it prompts you when the python code reaches out for a network connection.

**Comment by beerMT** [comment]
This is a screenshot of the notebook code cell.

<img width="1069" alt="Screen Shot 2020-05-27 at 9 06 40 AM" src="https://user-images.githubusercontent.com/6117308/83040437-7a42e200-9ffc-11ea-89a7-94abb309489f.png">

**Comment by beerMT** [comment]
This is being done in VScode on a newer MBP 16"

**Comment by ianhelle** [comment]
This is a bit odd
> I would have expected this elif block of code to fire since force_update is set to True 
in this case the elif path won't be taken since autoupdate is true and > 30 days alse

Can you check the contents of you ./max_mind_db path? It could be successfully downloading but we are failing to use the new version of the db. I would have expected an exception or warning if the download or extraction failed.

**Comment by beerMT** [comment]
Thanks @ianhelle for joining the discussion. The `$ ls -la` timestamp issue is one of the first things I checked when seeing if the update was successful. Pls see attached -  
<img width="717" alt="image" src="https://user-images.githubusercontent.com/6117308/83065985-9b69f980-a021-11ea-8b14-a07ea26e2214.png">

**Comment by beerMT** [comment]
Great talk btw - appreciated all the tooling you showcased 👍

**Comment by ashwin-patil** [comment]
Thanks @beerMT for providing the file listing. I am taking a look at it and get back to you with findings.

**Comment by ianhelle** [comment]
@beerMT - you might want to check this with the new 0.6.0/0.6.1 release. I did some changes to the logic in the GeoIP module. We weren't able to repro the issue but I did find a logic error in the if/else's that might have been the cause of making it think that the download had happened but not really happening.

**Comment by beerMT** [comment]
I think that may have done it. Thanks! Did a quick pip install --upgrade msticpy and ran the code block and I have pulled down fresh mmdbs! Much appreciated for working through that.
