### ISSUE TITLE
[Bug]: Query splitting on a pre-defined query returns a runtime error

### ISSUE THREAD

**Issue by cindraw** [microsoft/msticpy#705]
**Describe the bug**
A runtime error is raised when `split_query_by` argument is added when running a pre-defined query

**To Reproduce**

1. Import `QueryProvider` - `from msticpy.data.data_providers import QueryProvider`
2. Run any pre-defined query - `df = query_provider.ThreatIntelligence.list_indicators_by_ip(ip_address_list=['10.10.10.10'], start=datetime.now()-timedelta(days=2), end=datetime.now(), split_query_by='12H')`
3. See error on runtime exception that informs the user the event loop is already running

**Expected behavior**
Shows a widget that indicates the progress on query runtime as the code is being executed

**Screenshots and/or Traceback**
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[16], line 3
      1 delta = timedelta(days=2)
      2 # query_provider.list_queries()
----> 3 df = query_provider.ThreatIntelligence.list_indicators_by_ip(
      4     ip_address_list=['10.10.10.10'],
      5     start=datetime.now()-delta,
      6     end=datetime.now(),
      7     split_query_by='12H',
      8 )

File /opt/conda/lib/python3.10/site-packages/msticpy/data/core/data_providers.py:288, in QueryProvider._execute_query(self, *args, **kwargs)
    286 if split_by:
    287     logger.info("Split query selected - interval - %s", split_by)
--> 288     split_result = self._exec_split_query(
    289         split_by=split_by,
    290         query_source=query_source,
    291         query_params=params,
    292         debug=_debug_flag(*args, **kwargs),
    293         args=args,
    294         **kwargs,
    295     )
    296     if split_result is not None:
    297         return split_result

File /opt/conda/lib/python3.10/site-packages/msticpy/data/core/query_provider_connections_mixin.py:237, in QueryProviderConnectionsMixin._exec_split_query(self, split_by, query_source, query_params, **kwargs)
    235     logger.info("Running threaded queries.")
    236     event_loop = _get_event_loop()
--> 237     return event_loop.run_until_complete(
    238         self._exec_queries_threaded(query_tasks, progress, retry)
    239     )
    241 # or revert to standard synchronous execution
    242 return self._exec_synchronous_queries(progress, query_tasks)

File /opt/conda/lib/python3.10/asyncio/base_events.py:625, in BaseEventLoop.run_until_complete(self, future)
    614 """Run until the Future is done.
    615 
    616 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    622 Return the Future's result, or raise its exception.
    623 """
    624 self._check_closed()
--> 625 self._check_running()
    627 new_task = not futures.isfuture(future)
    628 future = tasks.ensure_future(future, loop=self)

File /opt/conda/lib/python3.10/asyncio/base_events.py:584, in BaseEventLoop._check_running(self)
    582 def _check_running(self):
    583     if self.is_running():
--> 584         raise RuntimeError('This event loop is already running')
    585     if events._get_running_loop() is not None:
    586         raise RuntimeError(
    587             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running
```

**Environment (please complete the following information):**

- Python Version: 2.10
- OS: Ubuntu
- Python environment: Jupyterhub
- MSTICPy Version: 2.7.0

**Comment by FlorianBracq** [comment]
Hello,

I'm not sure this is a msticpy bug compared to a jupyter bug?

From my (limited) understanding, the core issue is that Jupyter notebooks are alraedy executing the cell's code from an asyncio  loop, and calling an async function will create a nested loop that are by design not possible with asyncio.

This is explained in more details by more competent people than me here > https://bugs.python.org/issue22239

However, there is a workaround for this: the nest_asyncio package.
You have a few examples of it being used in the msticpy notebooks:
* docs/notebooks/ContiLeaksAnalysis.ipynb
* docs/notebooks/VTLookupV3.ipynb
```
import nest_asyncio
nest_asyncio.apply()
```

@ianhelle :
I noticed that this is directly packaged in the __init__ of `msticpy/context/lookup.py`, maybe that's worth adding in other places too?
