### ISSUE TITLE
Add certificate based authentication for data provider using an Azure AD Application

### ISSUE THREAD

**Issue by raggadhub** [microsoft/msticpy#713]
Hi dear MSTICPy contributors :smiley: ,

As you probably know, AAD/Entra administrators prefer to use certificate credentials whenever possible and don't use password credentials, also known as secrets.  [Security best practices for application properties in Azure Active Directory](https://learn.microsoft.com/en-us/azure/active-directory/develop/security-best-practices-for-app-registration#certificates-and-secrets)

It will be great to be able to use a certificate instead of a ClientSecret.
With the possibility to store the certificate in Azure Key Vault, and configure it using MpConfigEdit.

I will try to implement this feature but I do not know if I will succeed

**Comment by ianhelle** [comment]
Hi raggadhub. 
Some of this is already supported. E.g. if you have a certificate locally you can use Azure cert-based authentication, using auth_types=["certificate"].
I haven't tried this myself.
Also would be worth looking at the azure_kusto_driver - https://github.com/microsoft/msticpy/blob/da400e1b5a86938f322735ee34a3241172514af7/msticpy/data/drivers/azure_kusto_driver.py#L591

I'm not 100% certain whether this is consistent for all Azure endpoints - I think adding the cert into the connection string is probably somewhat specific to Kusto.

**Comment by ianhelle** [comment]
BTW I've submitted a PR that lets you use the Environment credential (auth_types=["env"] to provide a path to a certificate.
Not sure if this helps.
https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.environmentcredential?view=azure-python
This only works (as far as I can make out) for certs held in files (vs. in your local cert store - if you have this you can export to a PKCS12 cert/key file.

**Comment by raggadhub** [comment]
Hi Ian,

Many thanks for your clear answers, I will try and keep you informed.
