### ISSUE TITLE
[Bug]: AttributeError: 'LogsQueryPartialResult' object has no attribute 'tables' on large response limits.

### ISSUE THREAD

**Issue by JPvRiel** [microsoft/msticpy#714]
**Describe the bug**

Running a large query on `SigninLogs` table results in:

> AttributeError: 'LogsQueryPartialResult' object has no attribute 'tables'

**To Reproduce**

```
import msticpy as mp

qry_prov = mp.QueryProvider('MSSentinel')
qry_prov.connect(mp.WorkspaceConfig())
q_large = '''
SigninLogs
| take 100000
'''
captured_exception = None
try:
    result_large_query = qry_prov.exec_query(q_large)
except mp.common.exceptions.MsticpyDataQueryError as e:
    captured_exception = e
    print('Exception captured')
```

Exception that occured:

> AttributeError: 'LogsQueryPartialResult' object has no attribute 'tables'

Observe that the normal exception that happens with other tables, e.g. `SecurityEvent`, an "MsticpyDataQueryError" exception, does not occur for the above `SigninLogs` table. E.g. the following query gets the expected exception and not an AttributeError:

```python
q_large = '''
SecurityEvent
| take 100000
'''
```

**Expected behavior**

Expected a `MsticpyDataQueryError` with arguments "(ResponseSizeError) Response size too large" exception from mp.common.exceptions.MsticpyDataQueryError

**Screenshots and/or Traceback**

```console
Traceback (most recent call last):
  File "/home/test_user/demo/msticpy/bug.py", line 11, in <module>
    result_large_query = qry_prov.exec_query(q_win_sec_large)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test_user/.venv/secnb/lib/python3.11/site-packages/msticpy/data/core/data_providers.py", line 244, in exec_query
    return self._query_provider.query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test_user/.venv/secnb/lib/python3.11/site-packages/msticpy/data/drivers/azure_monitor_driver.py", line 305, in query
    data, result = self.query_with_results(query, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test_user/.venv/secnb/lib/python3.11/site-packages/msticpy/data/drivers/azure_monitor_driver.py", line 365, in query_with_results
    status = self._get_query_status(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test_user/.venv/secnb/lib/python3.11/site-packages/msticpy/data/drivers/azure_monitor_driver.py", line 543, in _get_query_status
    "tables": len(result.tables) if result.tables else 0,
                                    ^^^^^^^^^^^^^
AttributeError: 'LogsQueryPartialResult' object has no attribute 'tables'
```

**Environment (please complete the following information):**

- Python Version:  3.11
- OS: Ubuntu
- Python environment: venv with msticpy and dependencies pip installed.
- MSTICPy Version: 2.7.0

**Additional context**

Was simply trying to test out the feature described at https://msticpy.readthedocs.io/en/latest/data_acquisition/DataProviders.html#splitting-query-execution-into-chunks to help page through large amounts of data.

**Comment by ktb-jcm** [comment]
Also seeing this in the "A Getting Started Guide For Microsoft Sentinel ML Notebooks.ipynb" example notebook file provided in Microsoft Sentinel Notebooks. 
Running on an Azure Compute Instance STANDARD_DS3_V2.
Also being seen by at least one other co-worker.

**Comment by ktb-jcm** [comment]
Also seeing in the Microsoft example notebook "A Tour of Cybersec notebook features.ipynb" when using live data. attempting to run the cell that contains `logons_df = qry_prov.Azure.list_all_signins_geo()`.

Error log below:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[13], line 3
      1 # The QueryProvider will automatically
      2 # extract the "start" and "end" parameters from the query_time property to use in the query.
----> 3 logons_df = qry_prov.Azure.list_all_signins_geo()
      5 # You can also specify these parameters explicitly
      6 # logons_df = qry_prov.Azure.list_all_signins_geo(
      7 #     start=qry_prov.query_time.start, 
      8 #     end=qry_prov.query_time.end,
      9 # )
     11 if logons_df.empty:

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/msticpy/data/core/data_providers.py:314, in QueryProvider._execute_query(self, *args, **kwargs)
    310 query_options.update(self._get_query_options(params, kwargs))
    311 logger.info(
    312     "Running query '%s...' with params: %s", query_str[:40], query_options
    313 )
--> 314 return self.exec_query(query_str, query_source=query_source, **query_options)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/msticpy/data/core/data_providers.py:246, in QueryProvider.exec_query(self, query, **kwargs)
    244 logger.debug("Query options: %s", query_options)
    245 if not self._additional_connections:
--> 246     return self._query_provider.query(
    247         query, query_source=query_source, **query_options
    248     )
    249 return self._exec_additional_connections(query, **kwargs)

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/msticpy/data/drivers/azure_monitor_driver.py:292, in AzureMonitorDriver.query(self, query, query_source, **kwargs)
    290 if query_source:
    291     self._check_table_exists(query_source)
--> 292 data, result = self.query_with_results(query, **kwargs)
    293 return data if data is not None else result

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/msticpy/data/drivers/azure_monitor_driver.py:352, in AzureMonitorDriver.query_with_results(self, query, **kwargs)
    350     self._raise_unknown_error(unknown_err)
    351 result = cast(LogsQueryResult, result)
--> 352 status = self._get_query_status(result)
    353 logger.info("query status %s", repr(status))
    355 if isinstance(result, LogsQueryPartialResult):

File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/msticpy/data/drivers/azure_monitor_driver.py:531, in AzureMonitorDriver._get_query_status(result)
    527 @staticmethod
    528 def _get_query_status(result) -> Dict[str, Any]:
    529     status = {
    530         "status": result.status.name,
--> 531         "tables": len(result.tables) if result.tables else 0,
    532     }
    534     if isinstance(result, LogsQueryPartialResult):
    535         status["partial"] = "partial results returned"

AttributeError: 'LogsQueryPartialResult' object has no attribute 'tables'`
