### ISSUE TITLE
What happened to msticpy.iptools? 

### ISSUE THREAD

**Issue by mathurin68** [microsoft/msticpy#769]
Referencing here
https://msticpy.readthedocs.io/en/latest/data_acquisition/IPWhois.html

The below gives me 
ModuleNotFoundError: No module named 'msticpy.iptools'

```
>>> from msticpy.iptools import ip_whois
>>> ip_whois("65.55.44.109")
```

Thanks!!

**Comment by ianhelle** [comment]
Oh. I wonder if that is a doc error or that we've changed something.
These functions are still there. The source is msticpy.context.ip_utlils

```
from msticpy.context.ip_utils import ip_whois, ....
```

Alternatively you can use the same function via the pivot functions features

```
Ip.whois("123.1.2.5")
```

**Comment by ianhelle** [comment]
I'll update the docs

**Comment by mathurin68** [comment]
> Oh. I wonder if that is a doc error or that we've changed something. These functions are still there. The source is msticpy.context.ip_utlils
> 
> ```
> from msticpy.context.ip_utils import ip_whois, ....
> ```
> 
> Alternatively you can use the same function via the pivot functions features
> 
> ```
> Ip.whois("123.1.2.5")
> ```

@ianhelle   so sorry for the late response on this, thank you!!!  Thank you for all your hard work on this...I really wish I had more time to play with it!!
