### ISSUE TITLE
Azure Sentinel - add tag to incident?

### ISSUE THREAD

**Issue by glwallum** [microsoft/msticpy#773]
Trying to add a tag to an Azure Sentinel incident. I have tried using the update_items but have not been able to

Example code in Azure Machine Learning:

azs = MicrosoftSentinel()
azs.connect()
azs.update_incident(incident_id = "INCIDENTID", update_items = {'labels': [{'labelName': 'test', 'labelType': 'User'}]})

**Comment by petebryan** [comment]
This looks like it should work - @glwallum what sort of error do you get with this?

**Comment by ianhelle** [comment]
I've also reached out to the Sentinel engineering team to ask about this. The docs say that labels should be an array of LabelItem but don't actually give any examples of what the JSON representation of LabelItem should look like.
I think the dict that @glwallum is using would also be my best guess at what it *should* look like but it might be other weird structure embedded in string or something.

**Comment by glwallum** [comment]
> This looks like it should work - @glwallum what sort of error do you get with this?

I believe this was fixed by a pull request for adding labels

https://github.com/microsoft/msticpy/pull/774

**Comment by petebryan** [comment]
Oh brilliant, thanks
