### ISSUE TITLE
Can we disable SSL cert validation for Microsoft 365 Defender Provider ?

### ISSUE THREAD

**Issue by Tatsuya-hasegawa** [microsoft/msticpy#778]
Microsoft 365 Defender Provider cannot connect to the microsoft's server  in an environment due to SSL issue.
https://msticpy.readthedocs.io/en/latest/data_acquisition/DataProv-MSDefender.html

I understand it does not matter the SSL cert of microsoft and may possibly be from a vpn network problem.

I would like you to add the disable option for the SSL cert validation to escape the issue.

The trouble shooting for the issue is processing but please tell me if you already have the disable method.

Thank you!

**Comment by ianhelle** [comment]
Hmm - not sure how you do that. 
Do you have details?

**Comment by Tatsuya-hasegawa** [comment]
Thank you for your reply.
I got a solution of the ssl cert issue, so closed this.
